<?php
/**
 * Body1
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise Edition 2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Body1 Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Body1 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'body_1';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'entity_type_code' => 'string',
        'attribute_set' => '\Swagger\Client\Model\EavDataAttributeSetInterface',
        'skeleton_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'entity_type_code' => null,
        'attribute_set' => null,
        'skeleton_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'entity_type_code' => 'entityTypeCode',
        'attribute_set' => 'attributeSet',
        'skeleton_id' => 'skeletonId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'entity_type_code' => 'setEntityTypeCode',
        'attribute_set' => 'setAttributeSet',
        'skeleton_id' => 'setSkeletonId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'entity_type_code' => 'getEntityTypeCode',
        'attribute_set' => 'getAttributeSet',
        'skeleton_id' => 'getSkeletonId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['entity_type_code'] = isset($data['entity_type_code']) ? $data['entity_type_code'] : null;
        $this->container['attribute_set'] = isset($data['attribute_set']) ? $data['attribute_set'] : null;
        $this->container['skeleton_id'] = isset($data['skeleton_id']) ? $data['skeleton_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['entity_type_code'] === null) {
            $invalidProperties[] = "'entity_type_code' can't be null";
        }
        if ($this->container['attribute_set'] === null) {
            $invalidProperties[] = "'attribute_set' can't be null";
        }
        if ($this->container['skeleton_id'] === null) {
            $invalidProperties[] = "'skeleton_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['entity_type_code'] === null) {
            return false;
        }
        if ($this->container['attribute_set'] === null) {
            return false;
        }
        if ($this->container['skeleton_id'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets entity_type_code
     *
     * @return string
     */
    public function getEntityTypeCode()
    {
        return $this->container['entity_type_code'];
    }

    /**
     * Sets entity_type_code
     *
     * @param string $entity_type_code entity_type_code
     *
     * @return $this
     */
    public function setEntityTypeCode($entity_type_code)
    {
        $this->container['entity_type_code'] = $entity_type_code;

        return $this;
    }

    /**
     * Gets attribute_set
     *
     * @return \Swagger\Client\Model\EavDataAttributeSetInterface
     */
    public function getAttributeSet()
    {
        return $this->container['attribute_set'];
    }

    /**
     * Sets attribute_set
     *
     * @param \Swagger\Client\Model\EavDataAttributeSetInterface $attribute_set attribute_set
     *
     * @return $this
     */
    public function setAttributeSet($attribute_set)
    {
        $this->container['attribute_set'] = $attribute_set;

        return $this;
    }

    /**
     * Gets skeleton_id
     *
     * @return int
     */
    public function getSkeletonId()
    {
        return $this->container['skeleton_id'];
    }

    /**
     * Sets skeleton_id
     *
     * @param int $skeleton_id skeleton_id
     *
     * @return $this
     */
    public function setSkeletonId($skeleton_id)
    {
        $this->container['skeleton_id'] = $skeleton_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


